name: CI for smart contracts

on:
  push:
    branches:
    - master
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name:  install base software 
      run: |
        curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
        sudo apt-get install -y npm nodejs nodejs-npm git python g++ make
        npm install -g truffle ethereumjs-testrpc
        truffle compile
         
