name: CI for smart contracts

on:
  push:
    branches:
    - master
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name:  install base software 
      run: |
        curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
        sudo apt-get install -y npm nodejs git python g++ make
        sudo npm install -g truffle ethereumjs-testrpc
        sudo truffle compile
        
         
jobs: 
  test:
    name: test contracts
     run:
       sudo testrpc -p 8080 &
       sudo truffle test
       runs-on: ubuntu-latest
